### PR TITLE
Add freesurfer 7.3.0 and 7.3.1

### PR DESCRIPTION
**Pull request by jennydaman**

### CODE REVIEW

**Comment by yarikoptic** [comment]
just to make sure -- @jennydaman did you try building with both of those versions and had some basic testing of containers done? (since AFAIK there is no CI for such things here)

**Comment by jennydaman** [comment]
Ehe, perhaps the branch name `patch-1` revealed that I've been a little lazy here... 

It's building on my local machine rn and I'll follow up this afternoon.

**Comment by jennydaman** [comment]
Here's what I did to try the build:

```shell

git clone --branch patch-1 localhost/jennydaman/neurodocker:latest
cd neurodocker
docker build -t localhost/jennydaman/neurodocker .
mkdir freesurfer_example
cd freesurfer_example
docker run --rm -it localhost/jennydaman/neurodocker:latest \
	generate docker \
	    --pkg-manager apt \
	    --base-image debian:buster-slim \
	    --freesurfer version=7.3.1 \
	> Dockerfile
docker build -t localhost/jennydaman/neurodocker-freesurfer:7.3.1 .
```

I confirmed basic working state:

```shell
$ docker run --rm localhost/jennydaman/neurodocker-freesurfer:7.3.1 which recon-all
/opt/freesurfer-7.3.1/bin/recon-all
$ docker run --rm localhost/jennydaman/neurodocker-freesurfer:7.3.1 recon-all -version
freesurfer-linux-centos7_x86_64-7.3.1-20220723-115e466
```

**Comment by jennydaman** [comment]
@yarikoptic this is unexpected.

On my fork I enabled Actions and created a dummy PR, the same unit test fails on master. https://github.com/jennydaman/neurodocker/pull/1

**Comment by yarikoptic** [comment]
"cool", filed dedicated #460 

Let's proceed! Thank you!

**Comment by kaczmarj** [comment]
thanks @yarikoptic and @jennydaman 

we will look into the bug causing tests to fail. thanks for identifying this.

**Pull request merged**
