### PR TITLE
added _Renderer.labels method that enables adding labels with special chars in the label name

### PR DESCRIPTION
**Pull request by tclose**
As the title says, this PR addresses the issue raised in #444

### CODE REVIEW

**Comment by tclose** [comment]
Also fixes an apparent bug in the Singularity renderer where multiple labels weren't being separated by newlines

**Comment by tclose** [comment]
@kaczmarj do you have an ETA on the next Neurodocker release? I'm gearing up to make an Arcana release but need some bug fixes that are in the Neurodocker master

**Comment by kaczmarj** [comment]
@tclose - thanks for the PR and bugfix. looks good to me. i hadn't considered label names that had special characters.

would a release next week be good for you?

**Comment by tclose** [comment]
Hi @kaczmarj, no worries, thanks for the nice package! A release next week would be great.

**Comment by kaczmarj** [comment]
@tclose - i have not forgotten about this. grant writing is taking up all of my time and haven't found a good moment to do this. feel free to ping me here if i don't respond soon enough.

**Comment by tclose** [comment]
Hi @kaczmarj, any updates on the ETA of a new release? This is my only blocker at the moment

**Comment by kaczmarj** [comment]
@tclose - thanks for being patient with me... this grant is due wednesday night, so thursday will be new release.

image

**Comment by kaczmarj** [comment]
hi @tclose - release 0.9.1 is available! https://pypi.org/project/neurodocker/0.9.1/

and release notes are at https://github.com/ReproNim/neurodocker/releases

i released 0.9.0 with the changes from this pr (and a few others), but then i fixed another issue... so i released 0.9.1.

**Comment by tclose** [comment]
Awesome, thanks a lot!

**Pull request merged**
