### PR TITLE
[FIX] add "USER root" to top of every Dockerfile

### LINKED ISSUE #249: BUG: cannot build images when base is non-root
Always set `USER root` in the header when building.

### PR DESCRIPTION
**Pull request by jdkent**
ref #249 

first pass at forcing the user to be root.
Not going to say that this fixes #249 because this does not cover singularity builds.

I'm also unsure how this will interact with #270 if you want to primarily interact with the container as a user (not root).

### CODE REVIEW

**Comment by jdkent** [comment]
ping to see if anyone can review this pull request.

**Comment by kaczmarj** [comment]
sorry for the delay @jdkent - things were busy at school. i will test out this pr tomorrow. i'll check for interactions with #270

**Comment by kaczmarj** [comment]
@jdkent - i added a commit to implement similar behavior for singularity recipes. now this should fix #249 . once the tests pass, i will merge unless you have reservations

**Comment by jdkent** [comment]
The singularity issue for the miniconda test appears to be related to ContinuumIO/anaconda-issues#11163

**Comment by jdkent** [comment]
changed the singularity test to work with a previous version of miniconda, I suppose building a singularity with a newer version of miniconda will be defunct until some upstream changes are put into place.

@kaczmarj I believe this ready for review.

**Comment by kaczmarj** [comment]
Thank you so much for figuring out the issue. It was bugging me and I could not find the cause... my Google fu is not powerful enough yet. I will review tonight.

Best,
Jakub

**Comment by kaczmarj** [comment]
thank you @jdkent

**Pull request merged**
