### PR TITLE
[ENH] add templates bids_validator

### LINKED ISSUE #565: add install of bids validator
- will be very useful for anyone building a bids app
- probably best wait for the new version to be out before starting on that one.

### PR DESCRIPTION
**Pull request by Remi-Gau**
closes #565

could build an image with a dockerfile generated with the following

```bash
neurodocker generate docker --pkg-manager apt --base-image ubuntu:jammy-20221130 --bids_validator version=1.13
```

### CODE REVIEW

**Comment by Remi-Gau** [comment]
not tested with "yum" images

**Comment by Remi-Gau** [comment]
pinging @lamoglia who inspired me to finally open this PR (also because once this is part of neurodocker this will simplify the recipe for several BIDS app, including the base_validator image).

**Comment by kaczmarj** [comment]
this is a great addition! one suggestion is that the base image _could_ have nodejs and npm installed. could we check if npm exists before installing node? if npm already exists, we can use the existing installation to install the bids validator.

**Comment by Remi-Gau** [comment]
> this is a great addition! one suggestion is that the base image _could_ have nodejs and npm installed. could we check if npm exists before installing node? if npm already exists, we can use the existing installation to install the bids validator.

just to understand, why would you want to check this?

to avoid wasting build time or to avoid conflicting node / npm versions?

AFAIK the typical base image we use ubuntu, debian, fefora do not have node installed, right?

**Comment by kaczmarj** [comment]
It’s possible that a user could provide a different base image, for example one that already has nodejs in it. Or perhaps a user could have a custom RUN instruction that installs nodejs. We wouldn’t want to overwrite or reinstall nodejs and npm in those cases. The runtime is less of a concern imho — I would be more concerned about potentially overwriting an existing nodejs and causing unexpexted behavior.On Nov 10, 2023, at 11:42, Remi Gau ***@***.***> wrote:﻿

this is a great addition! one suggestion is that the base image could have nodejs and npm installed. could we check if npm exists before installing node? if npm already exists, we can use the existing installation to install the bids validator.

just to understand, why would you want to check this?
to avoid wasting build time or to avoid conflicting node / npm versions?
AFAIK the typical base image we use ubuntu, debian, fefora do not have node installed, right?

**Comment by Remi-Gau** [comment]
> this is a great addition! one suggestion is that the base image _could_ have nodejs and npm installed. could we check if npm exists before installing node? if npm already exists, we can use the existing installation to install the bids validator.

Done

**Review by kaczmarj — APPROVED** [review]

**Comment by kaczmarj** [comment]
thanks @Remi-Gau  :) merge at will!

**Pull request merged**
