### PR TITLE
[WIP] trying to update for FS7

### PR DESCRIPTION
**Pull request by mchlrnwld**
enable support for new freesurfer stable release 7.0

### CODE REVIEW

**Comment by kaczmarj** [comment]
thanks @mchlrnwld - can you merge master? the pr branch is out of date

**Comment by mchlrnwld** [comment]
sorry, this might exceed my expertise. i thought this would be the case? 
it says
_... wants to merge 1 commit into ReproNim:master from pwighton:20200430-fs7_

**Comment by kaczmarj** [comment]
no problem, i would suggest creating a new pull request from scratch. github makes this easy!

1. go to https://github.com/ReproNim/neurodocker/blob/master/neurodocker/templates/freesurfer.yaml
2. click the edit icon (the pencil to the right of `raw history blame`)
3. add the freesurfer 7 url
4. add a useful commit message
5. send a pr!

let me know if you need more help

**Comment by mchlrnwld** [comment]
done, thanks again!

**Comment by kaczmarj** [comment]
closed by #336

**Pull request closed without merging**
