### PR TITLE
[MAINT] update linting config and CI

### PR DESCRIPTION
**Pull request by Remi-Gau**
- update pre-commit config
  - update all the hooks
  - add hooks to format yaml and toml
- move several tooling config into pyproject.toml
- add ci wrokflow to
  - update pre-commit hooks regurlarly
  - let pre-commit handle all checks (may be worth using pre-commit CI: https://pre-commit.ci/

### CODE REVIEW

**Comment by Remi-Gau** [comment]
ouch... @stebo85 the yml auto-reformat is turning this simple PR into a monster of line changes.

let me know if you want me to move this to a different PR: I still believe that given how yml centric this repo is, we should have some style check on it

**Comment by Remi-Gau** [comment]
or I can at least put the yml reformat in a different commit run with datalad run.

**Review by stebo85 — APPROVED** [review]
great work! All the format changes are of course a bit annoying in this commit, but I think it's better going forward from here.

**Comment by Remi-Gau** [comment]
It was already there!! I think.

**Pull request merged**
