### PR TITLE
fix freeview

### PR DESCRIPTION
**Pull request by stebo85**

### CODE REVIEW

**Comment by Shotgunosine** [comment]
@kaczmarj Any chance of integrating this fix and cutting a new release of neurodocker? We've started using it for the neurodocker bids app and I'd like to build a version of the app for Freesurfer 7.1.0.
Thanks!

**Comment by kaczmarj** [comment]
sorry for the delay folks. originally, i intended neurodocker to create docker images without gui capabilities, because gui applications are finicky in containers. but i see that this PR (and related gui PRs) would be useful. 

i propose adding a flag to `--freesurfer` to install the gui-specific dependencies. i think this is a good idea because it would preserve the relatively small size of the recon-all minified containers, but would allow users to add gui dependencies for regular freesurfer installations.

**Comment by stebo85** [comment]
Dear @kaczmarj - a GUI flag is a great idea! Would it make sense to make it even more general and give every tool a GUI flag that we can then use in the recipes to add GUI components if needed? This would also apply to MrTrix, FSL, AFNI, MINC, MRIcron & SPM12 (which probably both don't make sense without the GUI flag :p)

**Comment by satra** [comment]
@stebo85 - do you have the bandwidth to attempt your suggestion, and rebase this on the current master?

**Comment by stebo85** [comment]
I can have a look at this after Christmas :)

**Comment by satra** [comment]
> I can have a look at this after Christmas :)

that would be awesome.

**Comment by stebo85** [comment]
I will wait with implementing a GUI option until the neurodocker rewrite to use reproenv is completed.

**Comment by kaczmarj** [comment]
>I will wait with implementing a GUI option until the neurodocker rewrite to use reproenv is completed.

@stebo85  - the rewrite is almost complete. I just have to add tests to make sure all of the templates are working properly. the code is in the branch [refactor/migrate-to-reproenv](https://github.com/ReproNim/neurodocker/tree/refactor/migrate-to-reproenv). feel free to peruse and see how a gui option could be included.

my thought is to add an optional argument like `gui` and then include logic in the template to install the gui dependencies.

i also uploaded a docker image of the current version of the rewrite.

```
docker run --rm kaczmarj/neurodocker-reproenv:devs-only generate docker --help
```

**Comment by stebo85** [comment]
closing - GUI option is added in Neurodesk build

**Pull request closed without merging**
