### PR TITLE
Add cat12

### PR DESCRIPTION
**Pull request by stebo85**
I added a template for CAT12. I tried to replicate the SPM12 template first, but I realised that hardcoding the Matlab environment in the CAT12 is not so good as the version might change in the future and it currently prevents the SPM12 template from being updated. If you like the approach of keeping the MCR out to reduce code duplication then we could also adjust the SPM12 template. It's probably not possible to combine different templates (e.g. insert the MCR template in the CAT12?)

I also had to adjust a few things in the MCR script to make the GUIs work in neurodesk - I hope that's ok.

I also tried to add documentation - I hope it's clear and helpful :)

This pull request also fixes the bug in https://github.com/ReproNim/neurodocker/issues/407

### CODE REVIEW

**Comment by stebo85** [comment]
The CI seems to fail due to a version problem when installing neurodocker in the CI - I am quite sure that I am not causing this problem :?

**Comment by kaczmarj** [comment]
@stebo85 -- thanks for the pr. the problem is with the requirements

```
black 22.1.0 depends on click>=8.0.0
```

but neurodocker uses `click<8.0`. let make a pr now simply changing the click version and see if the tests pass :)

**Comment by kaczmarj** [comment]
can you pull master?

**Comment by stebo85** [comment]
Fantastic :) All working now =)

**Comment by kaczmarj** [comment]
thank you @stebo85 ! and thanks for the ping

**Pull request merged**
