### PR TITLE
Parameratizing git remote for source builds

### PR DESCRIPTION
**Pull request by pwighton**
@kaczmarj, for your consideration:

This parameterizes references to git remotes.

At some point, I'd love to get FreeSurfer building from source in neurodocker, and this would be very handy for a development workflow.

### CODE REVIEW

**Comment by kaczmarj** [comment]
@pwighton - thanks, this is useful. i think instead of `fork`, i would prefer `repository`. would that be ok with you?  i'm being pedantic here, but fork might imply something other than the original source repository.

**Comment by pwighton** [comment]
Sure, `repository` or `repo` works for me.

**Comment by kaczmarj** [comment]
@pwighton - thanks, can you replace `fork` with `repo`? then this will be good to go.

**Comment by kaczmarj** [comment]
thanks for the useful feature @pwighton !

**Comment by pwighton** [comment]
Happy to help, @kaczmarj.  Thanks for all you do for neurodocker!

**Pull request merged**
