### PR TITLE
[DOC] update doc

### LINKED ISSUE #568: Ensure examples in doc can actually build
- [ ] they should use the latest distro available
- [ ] they should be example we know work (from the bootstrap workflow tests)
- [ ] ideally more complex build should be tested

### PR DESCRIPTION
**Pull request by Remi-Gau**
- closes #568 
- switch to using the latest distro / software versions in examples
- try to only show examples that are known to build
- comment out section of the doc that are not relevant given the build failure status of some softwares
- test the build of some of the examples
- leave out nipype example out of the doc until fixed

### CODE REVIEW

**Comment by kaczmarj** [comment]
thanks very much!! this will help us catch regressions and make sure we don't confuse our users with broken tutorials :)

**Comment by Remi-Gau** [comment]
am afraid the nipype tuto build will stay FUBAR for a little while
also I think it assumed that SPM would work with octave which is not something neurodocker supports anymore, right?

**Comment by Remi-Gau** [comment]
Not sure what to do about the nipype example: getting this one to work won't be that easy

**Comment by Remi-Gau** [comment]
tempted to leave the testing of the nipype example out of this PR and trying to fix it in a separate one though I suspect this will be more efficiently tackled by solving other problems we have

so I would recommend commenting out this example from the doc for now so as to not confuse users

**Pull request merged**
