### PR TITLE
installing minc from deb packages + mesa-drivers for register + extra…

### PR DESCRIPTION
**Pull request by stebo85**
Based on #332 - attempting to install Minctools from the provided debs - tested and working in ubuntu 18.04 and centos 7 images

### CODE REVIEW

**Comment by kaczmarj** [comment]
thank you @stebo85 - i will test this out

**Comment by djarecka** [comment]
@stebo85 - could you merge the current master, and I will test your branch, thank you.

@kaczmarj - do you have any specific requirements for new versions to be merge to neurodocker? Do you only test locally if the build is working or you set some automatic tests?

**Comment by Remi-Gau** [comment]
> @kaczmarj - do you have any specific requirements for new versions to be merge to neurodocker? Do you only test locally if the build is working or you set some automatic tests?

Though it was not designed exactly for this, the bootstrap workflow can be triggered manually from the `Action` tab, 

https://github.com/ReproNim/neurodocker/blob/dc3112fc415ba3352daf4bf980e731c74ea24d05/.github/workflows/bootstrap.yml#L36

though to test Minc it would need to be added to this dictionary: 

https://github.com/ReproNim/neurodocker/blob/dc3112fc415ba3352daf4bf980e731c74ea24d05/.github/workflows/create_workflows.py#L53

**Comment by stebo85** [comment]
closing this pull request here and I send a new pull request in https://github.com/ReproNim/neurodocker/pull/509

**Pull request closed without merging**
