### PR TITLE
Mcr missing deb libxp6

### PR DESCRIPTION
**Pull request by stebo85**
This deb file 

http://mirrors.kernel.org/debian/pool/main/libx/libxp/libxp6_1.0.2-2_amd64.deb

doesn't exist anymore and currently the build of a recipe fails because of it.

### CODE REVIEW

**Comment by kaczmarj** [comment]
thanks @stebo85 ! does this break any mcr functionality? do any of the executables link to `libxp` or `libXp`?

**Comment by mattcieslak** [comment]
This does seem to affect the AFNI builds on ubuntu. Any idea where that file went?

**Comment by stebo85** [comment]
It might only affect older MCRs? In my tests I couldn't find a negative side-effect of this missing yet

**Comment by kaczmarj** [comment]
@mattcieslak - i have opened https://github.com/ReproNim/neurodocker/issues/528 to track the missing libxp6 deb for afni. i do not know where the file went, but it seems like the package libxp6 in general is not available on debian (https://packages.debian.org/search?keywords=libxp) or ubuntu (https://packages.ubuntu.com/search?keywords=libxp&searchon=names&suite=kinetic&section=all)

**Pull request merged**
